/**
 * ARCHIVO GENERADO — NO EDITAR A MANO
 *
 * Fuente: _data/categorias-erp.csv (164 filas)
 * Regenerar: pnpm gen:familias
 *
 * Este mapa cruza el nombre CRUDO de la categoria del ERP (columna
 * `categoria` del proxy) con la familia comercial visible al usuario.
 * Los nombres del ERP van en MAYUSCULAS y con abreviaturas, no los edites.
 */

import type { FamiliaSlug } from "./familias-meta";

export interface CategoriaMapeada {
  familia: FamiliaSlug;
  /**
   * true si la categoria esta marcada como CONFIRMAR en el CSV (el cliente
   * aun no confirma si debe verse). Cuando el flag
   * OCULTAR_CATEGORIAS_POR_CONFIRMAR se activa, estas se filtran.
   */
  requiereConfirmacion?: boolean;
}

/** Map<nombre exacto del ERP, familia asignada>. */
export const CATEGORIA_A_FAMILIA: ReadonlyMap<string, CategoriaMapeada> = new Map([
  ["OTROS JUGUETES", { familia: "juguetes" }],
  ["PELUCHERIA GENERAL", { familia: "peluches" }],
  ["DISFRASES VARIOS", { familia: "disfraces-y-halloween" }],
  ["PINATERIA", { familia: "pinateria" }],
  ["DECORACION DE HOGAR", { familia: "decoracion-fiestas" }],
  ["HORA LOCA FIESTA", { familia: "decoracion-fiestas" }],
  ["JUEGO DIDACTICO", { familia: "juguetes" }],
  ["MUNECOS Y MUNECAS", { familia: "juguetes" }],
  ["DECORACION PARA FIESTAS", { familia: "decoracion-fiestas" }],
  ["ACCESORIOS DISFRAZ", { familia: "disfraces-y-halloween" }],
  ["FESTONERIA", { familia: "decoracion-fiestas" }],
  ["CAJA DE REGALO", { familia: "regalos-y-detalles" }],
  ["DESECHABLES PLASTICOS", { familia: "decoracion-fiestas" }],
  ["CARROS/MOTOS", { familia: "juguetes" }],
  ["DULCERIA CHOCOLATES", { familia: "dulceria-y-snacks" }],
  ["DE COSMETICOS", { familia: "cosmeticos-y-cuidado-personal" }],
  ["DESECHABLES DECORADOS", { familia: "decoracion-fiestas" }],
  ["ADORNOS NAVIDENOS", { familia: "navidad" }],
  ["MUNECOS, BRUJ/ADORNOS HALLOWEEN", { familia: "disfraces-y-halloween" }],
  ["MASCARAS HALLOWEEN", { familia: "disfraces-y-halloween" }],
  ["OTROS HALLOWEEN", { familia: "disfraces-y-halloween" }],
  ["JUEGOS DE MESAS", { familia: "juguetes" }],
  ["SOMBREROS Y GORROS HALLOWEEN", { familia: "disfraces-y-halloween" }],
  ["DULCERIA OTROS", { familia: "dulceria-y-snacks" }],
  ["INFLABLES", { familia: "decoracion-fiestas" }],
  ["DULCERIA GALLETAS", { familia: "dulceria-y-snacks" }],
  ["CRISTALRIA", { familia: "decoracion-fiestas" }],
  ["LLAVERO SURTIDO", { familia: "moda-y-accesorios" }],
  ["OTROS UTILES ESCOLAR", { familia: "escolar" }],
  ["PAPAS", { familia: "dulceria-y-snacks" }],
  ["CINTAS DE PAPEL/SEDA/ETC", { familia: "regalos-y-detalles" }],
  ["VELAS DECORATIVAS", { familia: "decoracion-fiestas" }],
  ["TECNOLOGIA (PARLANT-AUDIF-TECLAD)", { familia: "tecnologia-y-electronica" }],
  ["DULCERIA BANANAS Y BOMBONES", { familia: "dulceria-y-snacks" }],
  ["COLORES Y MARCADORES", { familia: "escolar" }],
  ["LIQUIDOS", { familia: "pinateria", requiereConfirmacion: true }],
  ["BOLSA REGALO SENCILLAS", { familia: "regalos-y-detalles" }],
  ["INSTRUMENTOS MUSICAL", { familia: "juguetes" }],
  ["TARJETERIA VARIOS MOTIVOS", { familia: "regalos-y-detalles" }],
  ["LUCES DE NAVIDAD", { familia: "navidad" }],
  ["VELAS FELIZ CUMPLEANOS", { familia: "decoracion-fiestas" }],
  ["MANTELERIA", { familia: "decoracion-fiestas" }],
  ["DECORACION MOBILIARIO FIESTAS", { familia: "decoracion-fiestas" }],
  ["LAMPARAS", { familia: "hogar-y-variedades" }],
  ["ARMAS Y BALDES HALLOWEEN", { familia: "disfraces-y-halloween" }],
  ["DE ASEO PERSONAL", { familia: "cosmeticos-y-cuidado-personal" }],
  ["DULCERIA ACIDOS", { familia: "dulceria-y-snacks" }],
  ["LICORES", { familia: "dulceria-y-snacks", requiereConfirmacion: true }],
  ["STICKERS", { familia: "escolar" }],
  ["BALONES Y OTRAS PELOTAS", { familia: "juguetes" }],
  ["BOLSOS", { familia: "moda-y-accesorios" }],
  ["BOLSA PARA EMPACAR", { familia: "regalos-y-detalles" }],
  ["RECORDATORIOS OTROS", { familia: "regalos-y-detalles" }],
  ["RELOJES", { familia: "moda-y-accesorios" }],
  ["PELUCAS Y BARBAS HALLOWEEN", { familia: "disfraces-y-halloween" }],
  ["CERVEZAS", { familia: "dulceria-y-snacks", requiereConfirmacion: true }],
  ["PINTURAS-LACAS-ESMALTES-MAQUILLAJE HALLW", { familia: "disfraces-y-halloween" }],
  ["TERMO/CANTIMPLORA/BOTELLAS", { familia: "hogar-y-variedades" }],
  ["BOLSA DE REGALO METALIZADA", { familia: "regalos-y-detalles" }],
  ["PISTOLAS DE AGUA", { familia: "juguetes" }],
  ["DESECHABLES EN ICOPOR", { familia: "decoracion-fiestas" }],
  ["MORRALES/MALETINES", { familia: "escolar" }],
  ["LAMINA/BASES DE ICOPOR", { familia: "pinateria" }],
  ["LAPIZ/BORRADOR", { familia: "escolar" }],
  ["MANI", { familia: "dulceria-y-snacks" }],
  ["GOMAS Y MILLOWS", { familia: "dulceria-y-snacks" }],
  ["CINTAS Y MALLAS DECORADAS", { familia: "regalos-y-detalles" }],
  ["AGUA", { familia: "dulceria-y-snacks" }],
  ["ACCESORIOS DE PESEBRE", { familia: "navidad" }],
  ["TARJETA DE INVITACION", { familia: "regalos-y-detalles" }],
  ["BOLSAS Y CAJAS DE SORPRESAS", { familia: "regalos-y-detalles" }],
  ["BILLETERAS", { familia: "moda-y-accesorios" }],
  ["ESTUCHE ESCOLAR", { familia: "escolar" }],
  ["CHILLONES", { familia: "juguetes" }],
  ["GASEOSAS", { familia: "dulceria-y-snacks" }],
  ["ANIMALES SURTIDOS", { familia: "juguetes" }],
  ["LIBRETAS", { familia: "escolar" }],
  ["SONAJEROS", { familia: "bebes" }],
  ["BATERIAS - CINTAS/ROLLOS FOTOGRAFICOS", { familia: "hogar-y-variedades" }],
  ["ACCESORIOS PARA MASCOTAS", { familia: "hogar-y-variedades" }],
  ["MONEDERO", { familia: "moda-y-accesorios" }],
  ["HORA LOCA HALLOWEEN", { familia: "disfraces-y-halloween" }],
  ["PORTARETRATOS", { familia: "regalos-y-detalles" }],
  ["CINTA TRANSPARENTE", { familia: "regalos-y-detalles" }],
  ["GAFAS Y ACCESOR PISCINA", { familia: "juguetes" }],
  ["CHICLETS", { familia: "dulceria-y-snacks" }],
  ["PAPEL DE REGALO TRADICIONAL", { familia: "regalos-y-detalles" }],
  ["BISUTERIA", { familia: "moda-y-accesorios" }],
  ["BOLSA DE REGALO TROQUELADA", { familia: "regalos-y-detalles" }],
  ["HERRAMIENTA DE TRABAJO", { familia: "hogar-y-variedades" }],
  ["SOMBRILLAS", { familia: "hogar-y-variedades" }],
  ["PATINETAS", { familia: "juguetes" }],
  ["TV - SONIDO - OTROS", { familia: "tecnologia-y-electronica" }],
  ["ARTICULOS PARA BEBE", { familia: "bebes" }],
  ["ENERGIZANTES", { familia: "dulceria-y-snacks" }],
  ["PINATAS EN PAPEL", { familia: "pinateria" }],
  ["PORCELANA EN CERAMICA", { familia: "hogar-y-variedades" }],
  ["CARTUCHERAS", { familia: "escolar" }],
  ["ESPADAS SURTIDAS", { familia: "juguetes" }],
  ["GORRAS", { familia: "moda-y-accesorios" }],
  ["ALCANCIAS", { familia: "regalos-y-detalles" }],
  ["MOVILES Y OTROS", { familia: "bebes" }],
  ["AVION, HELICOPTEROS,OBJETOS VOLADORES", { familia: "juguetes" }],
  ["CANGUROS", { familia: "bebes" }],
  ["PAPEL SEDA", { familia: "regalos-y-detalles" }],
  ["BOLIGRAFOS", { familia: "escolar" }],
  ["ALMENDRAS", { familia: "dulceria-y-snacks" }],
  ["SACAPUNTAS", { familia: "escolar" }],
  ["JUGOS", { familia: "dulceria-y-snacks" }],
  ["PINATAS EN ICOPOR", { familia: "pinateria" }],
  ["DIARIOS", { familia: "escolar" }],
  ["TETEROS", { familia: "bebes" }],
  ["LONCHERA", { familia: "escolar" }],
  ["TIJERAS", { familia: "escolar" }],
  ["VAJILLA DE BEBE", { familia: "bebes" }],
  ["PONQUES", { familia: "dulceria-y-snacks" }],
  ["PIMPOLINA", { familia: "bebes" }],
  ["BIENVENIDO EN ICOPOR", { familia: "pinateria" }],
  ["PAPEL TORNASOL", { familia: "regalos-y-detalles" }],
  ["PINTURA PARA GLOBOS", { familia: "pinateria" }],
  ["TE", { familia: "dulceria-y-snacks" }],
  ["LLAMA DIENTES Y CHUPOS", { familia: "bebes" }],
  ["CARTERAS", { familia: "moda-y-accesorios" }],
  ["CUADERNOS", { familia: "escolar" }],
  ["TRICICLOS", { familia: "juguetes" }],
  ["MOVILES", { familia: "bebes" }],
  ["TELARANA", { familia: "disfraces-y-halloween" }],
  ["PAPEL CREPE/CELOFAN", { familia: "regalos-y-detalles" }],
  ["PORCELANA CHINA", { familia: "hogar-y-variedades" }],
  ["SET COCINA/MUEBLES", { familia: "hogar-y-variedades" }],
  ["MOTIVO DE TORTA EN ICOPOR", { familia: "pinateria" }],
  ["IMPERMEABLE Y CARPAS", { familia: "juguetes" }],
  ["BINOCULARES", { familia: "juguetes" }],
  ["MUNECO CHILLON", { familia: "juguetes" }],
  ["BOMBONERA Y BANANERA DE ICOPOR", { familia: "pinateria" }],
  ["PORTALAPICEROS", { familia: "escolar" }],
  ["ARREGLOS Y COMBOS/DETALLES", { familia: "regalos-y-detalles" }],
  ["CAFE", { familia: "dulceria-y-snacks" }],
  ["CASA-CASTILLO-OTROS", { familia: "pinateria" }],
  ["WALKIE TALKIE", { familia: "tecnologia-y-electronica" }],
  ["BICICLETAS", { familia: "juguetes" }],
  ["TRENES/LOCOMOTORA", { familia: "juguetes" }],
  ["PRENDAS DE VESTIR SURT", { familia: "moda-y-accesorios" }],
  ["PAPEL FOAMY", { familia: "regalos-y-detalles", requiereConfirmacion: true }],
  ["TELEFONO", { familia: "tecnologia-y-electronica" }],
  ["BROMAS", { familia: "juguetes" }],
  ["MALTAS", { familia: "dulceria-y-snacks" }],
  ["CRISTOS VARIOS", { familia: "regalos-y-detalles" }],
  ["ARBOL NAVIDENO", { familia: "navidad" }],
  ["REGALERA EN ICOPOR", { familia: "pinateria" }],
  ["PAPEL METAL", { familia: "regalos-y-detalles", requiereConfirmacion: true }],
  ["GUANTES 1ra. COMUNION", { familia: "regalos-y-detalles" }],
  ["TIENDA EN ICOPOR", { familia: "pinateria" }],
  ["GUANTES/CASCOS/RODILLERAS OTROS", { familia: "juguetes" }],
  ["RECORDATORIOS BODA", { familia: "regalos-y-detalles" }],
  ["ROPA BEBE", { familia: "bebes" }],
  ["ROPA", { familia: "moda-y-accesorios" }],
  ["ZAPATOS", { familia: "moda-y-accesorios" }],
  ["VINO", { familia: "dulceria-y-snacks", requiereConfirmacion: true }],
  ["PAPEL ALUMINIO", { familia: "regalos-y-detalles", requiereConfirmacion: true }],
  ["ROSARIOS DE PRIMERA COMUNION", { familia: "regalos-y-detalles" }],
]);

/**
 * Categorias del ERP marcadas OCULTAR: nunca se muestran, sin flag.
 * Son consumo interno, transporte, o articulos discontinuados.
 */
export const CATEGORIAS_OCULTAS: ReadonlySet<string> = new Set([
  "CONSUMO INTERNO",
  "PORTA CD",
  "TRANSPORTE DOMICILIOS",
]);
